
export const DesignConstants = {
  INPUT_HEIGHT: 50,
  BUTTON_HEIGHT: 50,

  BORDER_WIDTH: 1,
  BORDER_RADIUS: 8,

  LOGO_REGULAR_WIDTH: 100, 
  LOGO_REGULAR_HEIGHT: 100,
  LOGO_SMALL_WIDTH: 50, 
  LOGO_SMALL_HEIGHT: 50,
};
