export const ar = {
  common: {
    appName: 'سيتي بالس',
    registerButton: 'تسجيل',
    success: 'نجاح',
    error: 'خطأ',
    ok: 'موافق',
    cancel: 'إلغاء',
    profile: 'الملف الشخصي',
    eventInfo: 'معلومات الفعالية',
    signup: 'تسجيل',
    pleaseLogin: 'يرجى تسجيل الدخول للمتابعة',
    passwordPlaceholder: 'كلمة المرور',
    passwordEmptyError: 'لا يمكن أن تكون كلمة المرور فارغة',
    usernameEmptyError: 'لا يمكن أن يكون اسم المستخدم فارغًا',
    usernamePlaceholder: 'اسم المستخدم',
    genericError: 'حدث خطأ غير متوقع.',
    usernameAlreadyTaken: 'اسم المستخدم مأخوذ بالفعل',
    emailAlreadyInUse: 'البريد الإلكتروني مستخدم بالفعل',
    failedtoDeleteAccount: 'فشل حذف الحساب. يرجى المحاولة مرة أخرى.',
    invalidCredentials: 'اسم المستخدم أو كلمة المرور غير صالحة',
    registrationFailed: 'فشل التسجيل. يرجى المحاولة مرة أخرى.',
    unknownError: 'حدث خطأ غير معروف'
  },
  loginScreen: {
    loginButton: 'تسجيل الدخول',
    signUpButton: 'تسجيل جديد',
    guestLoginButton: 'الدخول كزائر',
    apiError: 'فشل تسجيل الدخول. يرجى التحقق من بيانات الاعتماد الخاصة بك.',
  },
  signUpScreen: {
    emailPlaceholder: 'البريد الإلكتروني',
    reEnterPasswordPlaceholder: 'أعد إدخال كلمة المرور',
    usernameLengthError: 'يجب أن يكون اسم المستخدم أقل من 12 حرفًا',
    emailEmptyError: 'البريد الإلكتروني مطلوب',
    emailInvalidError: 'الرجاء إدخال عنوان بريد إلكتروني صالح',
    passwordInvalidError: 'يجب أن تتكون كلمة المرور من 4-24 حرفًا، وتحتوي على حرف واحد ورقم واحد على الأقل',
    passwordMismatchError: 'كلمات المرور غير متطابقة',
    passwordPlaceholder: 'كلمة المرور',
    registrationSuccess: 'تم التسجيل بنجاح! يمكنك الآن تسجيل الدخول.',
  },
  homeScreeen: {
    welcomeMessage: 'أهلاً بك',
    noEventsFound: 'لم يتم العثور على فعاليات',
    searchPlaceholder: 'ابحث عن الفعاليات...',
  },
  eventDetailsScreen: {
    title: 'معلومات الفعالية',
    venue: 'المكان',
    date: 'التاريخ',
    invalidLocationData: 'بيانات الموقع غير صالحة.',
    locationOnMap: 'موقع الفعالية',
    tapToOpenInMaps: 'اضغط للفتح في الخرائط',
  },
  profileScreen: {
    logout: 'تسجيل الخروج',
    delete: 'حذف',
    deleteAccount: 'حذف الحساب',
    deleteAccountConfirmation: 'هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.',
    logoutConfirmation: 'هل أنت متأكد من أنك تريد تسجيل الخروج؟',
  },
};
